### PR TITLE
add additional source protocol

### PR DESCRIPTION
**Pull request by lewis6991**
- added: luarocks
- Weaken the URL pattern. Implementations can implement any protocol
  they want.

### CODE REVIEW

**Comment by bew** [comment]
How / Where would that list of supported protocols defined in code?

**Comment by lewis6991** [comment]
That's not really an intended goal and I'm not sure of any benefits it would provide.

**Comment by mjlbach** [comment]
Also need to update the readme

**Comment by mjlbach** [comment]
What is the advantage of the github/gitlab specific URIs compared to just pointing git+ correctly?

**Review by mjlbach — APPROVED** [review]

**Pull request merged**
