### PR TITLE
feat: add jsonschema

### PR DESCRIPTION
**Pull request by lewis6991**

### CODE REVIEW

**Comment by mjlbach** [comment]
In favor of this once things are more solidified, although we could just update the PR and merge it as-is, and keep things up to date with future PRs :)

**Comment by mjlbach** [comment]
@lewis6991 would you mind bringing this up to date?

**Comment by lewis6991** [comment]
Sure. Can only find short pockets of time for OSS atm. Will make this first priority.

**Comment by mjlbach** [comment]
No worries! I appreciate your contribution and am very glad you are taking out time to contribute to this :)

**Comment by lewis6991** [comment]
FInally added some plumbing so we can run the schema on examples.

**Pull request merged**
